/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

/**
 *
 * @author PC
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Forgetpass1 extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    String pass ;
    String repass ;
    String email ;
    String email1;
    String pass1;
    String repass1;
    String otp2="9068";
   int i;
   String otp;
   
    public Forgetpass1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        temail = new javax.swing.JTextField();
        tpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bback = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        trepass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bsubmit = new javax.swing.JLabel();
        totp = new javax.swing.JLabel();
        jotp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temail.setBackground(new java.awt.Color(0, 0, 0));
        temail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        temail.setForeground(new java.awt.Color(255, 255, 255));
        temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 25));

        tpass.setBackground(new java.awt.Color(0, 0, 0));
        tpass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 25));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 110, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 120, 20));

        bback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/back.png"))); // NOI18N
        bback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbackMouseClicked(evt);
            }
        });
        jPanel1.add(bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Your New Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 210, -1));

        trepass.setBackground(new java.awt.Color(0, 0, 0));
        trepass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        trepass.setForeground(new java.awt.Color(255, 255, 255));
        trepass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(trepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 95, 180, 25));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Email ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        bsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/submit (1).png"))); // NOI18N
        bsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(bsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 175, 120, -1));

        totp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        totp.setForeground(new java.awt.Color(255, 255, 255));
        totp.setText("Generate Otp");
        totp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        totp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totpMouseClicked(evt);
            }
        });
        jPanel1.add(totp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jotp.setBackground(new java.awt.Color(255, 255, 255));
        jotp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jotp.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 85, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/web.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
        
        
        
    private void bbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbackMouseClicked
        // TODO add your handling code here:
        Login lo = new Login();
        lo.show();
        dispose();
        
    }//GEN-LAST:event_bbackMouseClicked

    private void bsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsubmitMouseClicked
        // TODO add your handling code here:
         pass = tpass.getText();
         repass = trepass.getText();
         email = temail.getText();
        otp = jotp.getText();
  
        if(pass.equals(repass))
        {
        if(tpass.getText().equals("")||trepass.getText().equals("")||temail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(bsubmit,"please fill out all fields");
        }
        else
        {
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","1234");
                String url = "SELECT * FROM user WHERE email=?";
                PreparedStatement ps=con.prepareStatement(url);
                ps.setString(1,email);
                ResultSet rs = ps.executeQuery();
               
                while(rs.next())
                {
                  email1=rs.getString(2);
                   pass1=rs.getString(3);
                    repass1=rs.getString(4);
                      System.out.print(email1+""+pass1+""+repass1);
                    
                }
                
                if(email.equals(email1))
                {
            try
            {
               
                 if(otp.equals(otp2))
                {
                System.out.print("hello3");
                String url1="UPDATE user SET password=?,repassword=? WHERE email=?";
               PreparedStatement ps1 = con.prepareStatement(url1);
               System.out.print("hello");
               ps1.setString(1,pass);
               ps1.setString(2,repass);
               ps1.setString(3,email);
               System.out.print(email+""+pass+""+repass);
                i=ps1.executeUpdate();
               System.out.print("hello");
                }
                 else
                 {
                JOptionPane.showMessageDialog(bsubmit,"Otp Does not Match");
                 }
                 
               if(i!=0)
               {
                JOptionPane.showMessageDialog(bsubmit,"New Password success");
                con.close();
          
                 Login lo =new Login();
                 lo.show();
                 dispose();
              }
               else
               {
                   System.out.println("try again   ");
               }
               
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
                    
                   
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(bsubmit,"Email Does Not Match");
                }
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
                
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(bsubmit,"Password Does Not Match");
        }
  
    }//GEN-LAST:event_bsubmitMouseClicked

    private void totpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totpMouseClicked
        // TODO add your handling code here:
        Otpsend op = new Otpsend();
        op.sendSms();
        
    }//GEN-LAST:event_totpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgetpass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgetpass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgetpass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgetpass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgetpass1().setVisible(true);
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bback;
    private javax.swing.JLabel bsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jotp;
    private javax.swing.JTextField temail;
    private javax.swing.JLabel totp;
    private javax.swing.JTextField tpass;
    private javax.swing.JTextField trepass;
    // End of variables declaration//GEN-END:variables
}
