/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

/**
 *
 * @author PC
 */
import java.sql.*;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
     
    String pass;
     String pass1;
    String name;
    String email1;
    String repass1;
    String country1;
    String state1;
    String phone1;
     String name1;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpass = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blogin = new rojerusan.RSMaterialButtonCircle();
        breg = new javax.swing.JLabel();
        forgetpass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpass.setBackground(new java.awt.Color(0, 0, 0));
        tpass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setText("Enter your password");
        tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tpass.setCaretColor(new java.awt.Color(0, 0, 0));
        tpass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 140, 220, 30));

        tname.setBackground(new java.awt.Color(0, 0, 0));
        tname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tname.setForeground(new java.awt.Color(255, 255, 255));
        tname.setText("Enter your username");
        tname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 89, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/user1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 50, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" to the world of dreams");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 190, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WELCOME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/login2 (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 220));

        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel1.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 210, 200, 35));

        breg.setBackground(new java.awt.Color(255, 255, 255));
        breg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        breg.setForeground(new java.awt.Color(255, 255, 255));
        breg.setText("               Registration");
        breg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        breg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bregMouseClicked(evt);
            }
        });
        jPanel1.add(breg, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 250, 190, 20));

        forgetpass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        forgetpass.setForeground(new java.awt.Color(255, 255, 255));
        forgetpass.setText("Forget password");
        forgetpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpassMouseClicked(evt);
            }
        });
        jPanel1.add(forgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 175, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/img/web.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 375));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:
         pass = tpass.getText();
          name = tname.getText();
    
        if(tpass.getText().equals("")||tname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(blogin,"please fill out all fields");
        }
        else
       {
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","1234");
                String url = "SELECT * FROM user WHERE email=?";
                PreparedStatement ps=con.prepareStatement(url);
                ps.setString(1,name);
                ResultSet rs = ps.executeQuery();
               
                while(rs.next())
                {
                   name1=rs.getString(1);
                   email1=rs.getString(2);
                   pass1=rs.getString(3);
                   repass1=rs.getString(4);
                   country1=rs.getString(5);
                   state1=rs.getString(6);
                   phone1=rs.getString(7);
                   
                      System.out.print(email1+""+pass1);
                    
                }
                
                if(!name.equals(email1))
                {
                        JOptionPane.showMessageDialog(blogin,"Email Does Not Match");
                        System.out.print(email1+""+name);
                 }
                else if(!pass.equals(pass1))
                 {
                       JOptionPane.showMessageDialog(blogin,"password Does Not Match");
                 }
                
                 else
                {
                    
                    Dashboard db=new Dashboard();
                    db.data(name1,email1,pass1,repass1,country1,state1,phone1);
                    db.show();
                    System.out.print("hello");
                    dispose();
                }
                   
                    
                      
            }
            catch(Exception e)
            {
                e.printStackTrace();
                
            }
        }
     
        
    }//GEN-LAST:event_bloginActionPerformed

    private void bregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bregMouseClicked
        // TODO add your handling code here:
        Registration re = new Registration();
        re.show();
        
          dispose(); 
    }//GEN-LAST:event_bregMouseClicked

    private void forgetpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassMouseClicked
        // TODO add your handling code here:
       
        Forgetpass1 op = new Forgetpass1();
        op.show();
        dispose();
    }//GEN-LAST:event_forgetpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle blogin;
    private javax.swing.JLabel breg;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tpass;
    // End of variables declaration//GEN-END:variables
}
